///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TaskSchedule_LA_metroexpresslanes
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Login recording.
    /// </summary>
    [TestModule("c3154aa2-9eeb-42ae-a68f-8530dd0ce076", ModuleType.Recording, 1)]
    public partial class Login : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TaskSchedule_LA_metroexpresslanesRepository repository.
        /// </summary>
        public static TaskSchedule_LA_metroexpresslanesRepository repo = TaskSchedule_LA_metroexpresslanesRepository.Instance;

        static Login instance = new Login();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Login()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Login Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://www.metroexpresslanes.net' with browser 'Chrome' in maximized mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("https://www.metroexpresslanes.net", "Chrome", "", false, true, false, false, false, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MetroExpresslanes1.Login' at Center.", repo.MetroExpresslanes1.LoginInfo, new RecordItemIndex(1));
            repo.MetroExpresslanes1.Login.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'METROEXPRESSLANES.Username' at Center.", repo.METROEXPRESSLANES.UsernameInfo, new RecordItemIndex(2));
            repo.METROEXPRESSLANES.Username.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'KerrSmoke' with focus on 'METROEXPRESSLANES.Username'.", repo.METROEXPRESSLANES.UsernameInfo, new RecordItemIndex(3));
            repo.METROEXPRESSLANES.Username.PressKeys("KerrSmoke");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'METROEXPRESSLANES.Password' at Center.", repo.METROEXPRESSLANES.PasswordInfo, new RecordItemIndex(4));
            repo.METROEXPRESSLANES.Password.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'S@ndieg0' with focus on 'METROEXPRESSLANES.Password'.", repo.METROEXPRESSLANES.PasswordInfo, new RecordItemIndex(5));
            repo.METROEXPRESSLANES.Password.PressKeys("S@ndieg0");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'METROEXPRESSLANES.Login' at Center.", repo.METROEXPRESSLANES.LoginInfo, new RecordItemIndex(6));
            repo.METROEXPRESSLANES.Login.Click();
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
