///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TaskSchedule_LA_metroexpresslanes
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The LogOut recording.
    /// </summary>
    [TestModule("9d6528d5-135b-4184-b552-75cf49048345", ModuleType.Recording, 1)]
    public partial class LogOut : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TaskSchedule_LA_metroexpresslanesRepository repository.
        /// </summary>
        public static TaskSchedule_LA_metroexpresslanesRepository repo = TaskSchedule_LA_metroexpresslanesRepository.Instance;

        static LogOut instance = new LogOut();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public LogOut()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static LogOut Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(0));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'METROEXPRESSLANES.UserButton' at 146;17.", repo.METROEXPRESSLANES.UserButtonInfo, new RecordItemIndex(1));
            repo.METROEXPRESSLANES.UserButton.Click("146;17");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(2));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'METROEXPRESSLANES.Logout' at 27;5.", repo.METROEXPRESSLANES.LogoutInfo, new RecordItemIndex(3));
            repo.METROEXPRESSLANES.Logout.Click("27;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(4));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'METROEXPRESSLANES.LoginContainerNgScope'.", repo.METROEXPRESSLANES.LoginContainerNgScopeInfo, new RecordItemIndex(5));
            Validate.Exists(repo.METROEXPRESSLANES.LoginContainerNgScopeInfo);
            Delay.Milliseconds(100);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.METROEXPRESSLANES.LoginContainerNgScope, false, new RecordItemIndex(6));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
