///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace TaskSchedule_LA_metroexpresslanes
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TaskSchedule_LA_metroexpresslanesRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("1bab5ec2-261c-41d6-9174-e46573a07dfe")]
    public partial class TaskSchedule_LA_metroexpresslanesRepository : RepoGenBaseFolder
    {
        static TaskSchedule_LA_metroexpresslanesRepository instance = new TaskSchedule_LA_metroexpresslanesRepository();
        TaskSchedule_LA_metroexpresslanesRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        TaskSchedule_LA_metroexpresslanesRepositoryFolders.METROEXPRESSLANESAppFolder _metroexpresslanes;

        /// <summary>
        /// Gets the singleton class instance representing the TaskSchedule_LA_metroexpresslanesRepository element repository.
        /// </summary>
        [RepositoryFolder("1bab5ec2-261c-41d6-9174-e46573a07dfe")]
        public static TaskSchedule_LA_metroexpresslanesRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TaskSchedule_LA_metroexpresslanesRepository() 
            : base("TaskSchedule_LA_metroexpresslanesRepository", "/", null, 0, false, "1bab5ec2-261c-41d6-9174-e46573a07dfe", ".\\RepositoryImages\\TaskSchedule_LA_metroexpresslanesRepository1bab5ec2.rximgres")
        {
            _applicationundertest = new TaskSchedule_LA_metroexpresslanesRepositoryFolders.ApplicationUnderTestAppFolder(this);
            _metroexpresslanes = new TaskSchedule_LA_metroexpresslanesRepositoryFolders.METROEXPRESSLANESAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("1bab5ec2-261c-41d6-9174-e46573a07dfe")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("45c25457-3b0c-48ff-856e-b4cca1f10145")]
        public virtual TaskSchedule_LA_metroexpresslanesRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The METROEXPRESSLANES folder.
        /// </summary>
        [RepositoryFolder("c7f4e168-7933-4613-8f2d-8d483d301c29")]
        public virtual TaskSchedule_LA_metroexpresslanesRepositoryFolders.METROEXPRESSLANESAppFolder METROEXPRESSLANES
        {
            get { return _metroexpresslanes; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class TaskSchedule_LA_metroexpresslanesRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("45c25457-3b0c-48ff-856e-b4cca1f10145")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.ranorex.com']", parentFolder, 30000, null, false, "45c25457-3b0c-48ff-856e-b4cca1f10145", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("45c25457-3b0c-48ff-856e-b4cca1f10145")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("45c25457-3b0c-48ff-856e-b4cca1f10145")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The METROEXPRESSLANESAppFolder folder.
        /// </summary>
        [RepositoryFolder("c7f4e168-7933-4613-8f2d-8d483d301c29")]
        public partial class METROEXPRESSLANESAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _userbuttonInfo;
            RepoItemInfo _logoutInfo;
            RepoItemInfo _logincontainerngscopeInfo;

            /// <summary>
            /// Creates a new METROEXPRESSLANES  folder.
            /// </summary>
            public METROEXPRESSLANESAppFolder(RepoGenBaseFolder parentFolder) :
                    base("METROEXPRESSLANES", "/dom[@domain='lametrobos.metroexpresslanes.net']", parentFolder, 30000, null, false, "c7f4e168-7933-4613-8f2d-8d483d301c29", "")
            {
                _userbuttonInfo = new RepoItemInfo(this, "UserButton", ".//button[#'user-button']", 30000, null, "bf522e3a-8505-4183-84d6-484bd7ce18d1");
                _logoutInfo = new RepoItemInfo(this, "Logout", ".//div[#'user-dropdown-menu']/?/?/span[@innertext='Logout']", 30000, null, "ba7cb74d-92bc-4fcd-b63f-9a13e5b57e4f");
                _logincontainerngscopeInfo = new RepoItemInfo(this, "LoginContainerNgScope", "body/div/div", 30000, null, "365d1b3e-638e-4207-8eb3-572911ff4e0f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c7f4e168-7933-4613-8f2d-8d483d301c29")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c7f4e168-7933-4613-8f2d-8d483d301c29")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The UserButton item.
            /// </summary>
            [RepositoryItem("bf522e3a-8505-4183-84d6-484bd7ce18d1")]
            public virtual Ranorex.ButtonTag UserButton
            {
                get
                {
                    return _userbuttonInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The UserButton item info.
            /// </summary>
            [RepositoryItemInfo("bf522e3a-8505-4183-84d6-484bd7ce18d1")]
            public virtual RepoItemInfo UserButtonInfo
            {
                get
                {
                    return _userbuttonInfo;
                }
            }

            /// <summary>
            /// The Logout item.
            /// </summary>
            [RepositoryItem("ba7cb74d-92bc-4fcd-b63f-9a13e5b57e4f")]
            public virtual Ranorex.SpanTag Logout
            {
                get
                {
                    return _logoutInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Logout item info.
            /// </summary>
            [RepositoryItemInfo("ba7cb74d-92bc-4fcd-b63f-9a13e5b57e4f")]
            public virtual RepoItemInfo LogoutInfo
            {
                get
                {
                    return _logoutInfo;
                }
            }

            /// <summary>
            /// The LoginContainerNgScope item.
            /// </summary>
            [RepositoryItem("365d1b3e-638e-4207-8eb3-572911ff4e0f")]
            public virtual Ranorex.DivTag LoginContainerNgScope
            {
                get
                {
                    return _logincontainerngscopeInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The LoginContainerNgScope item info.
            /// </summary>
            [RepositoryItemInfo("365d1b3e-638e-4207-8eb3-572911ff4e0f")]
            public virtual RepoItemInfo LoginContainerNgScopeInfo
            {
                get
                {
                    return _logincontainerngscopeInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
